@echo off
set OLLAMA_GPU_OVERHEAD=1024000000
set OLLAMA_MAX_LOADED_MODELS=1
set OLLAMA_CONTEXT_LENGTH=2048
set OLLAMA_SCHED_SPREAD=0
set OLLAMA_MAX_QUEUE=1

echo Ollama Environment Variables Set:
echo OLLAMA_GPU_OVERHEAD: %OLLAMA_GPU_OVERHEAD%
echo OLLAMA_MAX_LOADED_MODELS: %OLLAMA_MAX_LOADED_MODELS%
echo OLLAMA_CONTEXT_LENGTH: %OLLAMA_CONTEXT_LENGTH%
echo OLLAMA_SCHED_SPREAD: %OLLAMA_SCHED_SPREAD%
echo OLLAMA_MAX_QUEUE: %OLLAMA_MAX_QUEUE%

pause
